# Generated by Django 5.2 on 2025-05-30 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=20, unique=True)),
                ('chief_complaint', models.TextField()),
                ('symptom_details', models.TextField()),
                ('pain_scale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mr_code', models.CharField(max_length=20, unique=True)),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_medical_records', to='emr.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='emr.patient')),
            ],
        ),
    ]
