# Generated by Django 5.2 on 2025-05-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_medicalrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='symptom_details',
            new_name='symptome_details',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='mrn',
        ),
    ]
