# Generated by Django 5.2 on 2025-06-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0003_rename_symptom_details_medicalrecord_symptome_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.TextField()),
                ('diferential_diagnosis', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='emr.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='HPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpis', to='emr.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PatientInTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField()),
                ('past_medical_history', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('allergies', models.TextField()),
                ('family_history', models.TextField(blank=True)),
                ('social_history', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_forms', to='emr.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('ai_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='emr.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='emr.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewOfSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.TextField(blank=True, null=True)),
                ('skin', models.TextField(blank=True, null=True)),
                ('heent', models.TextField(blank=True, null=True)),
                ('neck', models.TextField(blank=True, null=True)),
                ('breasts', models.TextField(blank=True, null=True)),
                ('respiratory', models.TextField(blank=True, null=True)),
                ('cardiovascular', models.TextField(blank=True, null=True)),
                ('gastrointestinal', models.TextField(blank=True, null=True)),
                ('genitourinary', models.TextField(blank=True, null=True)),
                ('endocrine', models.TextField(blank=True, null=True)),
                ('neurological', models.TextField(blank=True, null=True)),
                ('psychiatric', models.TextField(blank=True, null=True)),
                ('musculoskeletal', models.TextField(blank=True, null=True)),
                ('hematologic_lymphatic', models.TextField(blank=True, null=True)),
                ('allergic_immunologic', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_of_systems', to='emr.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_rate', models.FloatField()),
                ('respiratory_rate', models.FloatField()),
                ('temprature', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('blood_oxygen_saturation', models.CharField(max_length=10)),
                ('balance', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='emr.medicalrecord')),
            ],
        ),
    ]
