# Generated by Django 5.2 on 2025-06-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0004_assessment_hpi_patientintake_plan_prescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='Note',
            new_name='assessment_note',
        ),
        migrations.RenameField(
            model_name='hpi',
            old_name='Note',
            new_name='hpi_note',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='note',
            new_name='plan_note',
        ),
    ]
