# Generated by Django 5.2 on 2025-06-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0005_rename_note_assessment_assessment_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientintake',
            name='history_of_present_illness',
        ),
    ]
